
# ██████╗░░█████╗░███╗░░██╗███████╗███╗░░░███╗███████╗░█████╗░██╗░░░░░░█████╗░██████╗░██╗░░░░░███████╗
# ██╔══██╗██╔══██╗████╗░██║██╔════╝████╗░████║██╔════╝██╔══██╗██║░░░░░██╔══██╗██╔══██╗██║░░░░░██╔════╝
# ██████╦╝██║░░██║██╔██╗██║█████╗░░██╔████╔██║█████╗░░███████║██║░░░░░███████║██████╦╝██║░░░░░█████╗░░
# ██╔══██╗██║░░██║██║╚████║██╔══╝░░██║╚██╔╝██║██╔══╝░░██╔══██║██║░░░░░██╔══██║██╔══██╗██║░░░░░██╔══╝░░
# ██████╦╝╚█████╔╝██║░╚███║███████╗██║░╚═╝░██║███████╗██║░░██║███████╗██║░░██║██████╦╝███████╗███████╗
# ╚═════╝░░╚════╝░╚═╝░░╚══╝╚══════╝╚═╝░░░░░╚═╝╚══════╝╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═════╝░╚══════╝╚══════╝
#
# ░██████╗██╗░░░██╗░██████╗░░█████╗░██████╗░░░░█████╗░░█████╗░███╗░░██╗███████╗
# ██╔════╝██║░░░██║██╔════╝░██╔══██╗██╔══██╗░░██╔══██╗██╔══██╗████╗░██║██╔════╝
# ╚█████╗░██║░░░██║██║░░██╗░███████║██████╔╝░░██║░░╚═╝███████║██╔██╗██║█████╗░░
# ░╚═══██╗██║░░░██║██║░░╚██╗██╔══██║██╔══██╗░░██║░░██╗██╔══██║██║╚████║██╔══╝░░
# ██████╔╝╚██████╔╝╚██████╔╝██║░░██║██║░░██║░░╚█████╔╝██║░░██║██║░╚███║███████╗
# ╚═════╝░░╚═════╝░░╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚════╝░╚═╝░░╚═╝╚═╝░░╚══╝╚══════╝

# Plugin Settings
settings:

  # Language
  # Change the language of the plugin.
  # Supported languages:
  #  - English   (en_US)
  #  - German    (de_DE)
  #  - French    (fr_FR)
  #  - Finnish   (fi_FI)
  #  - Polish    (pl_PL)
  #  - Dutch     (nl_NL)
  language: "en_US"

  # Grow-by-one-block
  # If true, bone meal grows sugar cane by exactly 1 block.
  # If false, bone meal grows sugar cane up to the maximum height of 3 blocks at once.
  grow-by-one-block: false

  # Spawn Particles
  # Whether to spawn particles when sugar cane is bone-mealed.
  spawn-particles: true

  # Play Sound
  # Whether to play a sound effect when sugar cane is bone-mealed.
  play-sound: true

# Leave these options alone unless you know what you're doing.
config:
  version: 1.0.0
